---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
-
  name: area/ci
  description: Continuous Integration
  color: 4a97d6
-
  name: area/python
  description: Pull requests that update Python code
  color: 2b67c6
-
  name: "bot"
  color: "69cde9"
  description: ""
-
  name: github_actions
  description: Pull requests that update Github_actions code
  color: "000000"
-
  name: good first issue
  description: Good for newcomers
  color: 7057ff
-
  name: help wanted
  description: Extra attention is needed
  color: 008672
-
  name: kind/breaking
  description: Breaking Changes
  color: bfd4f2
-
  name: kind/bug
  description: Something isn't working
  color: d73a4a
-
  name: kind/build
  description: Build System and Dependencies
  color: bfdadc
-
  name: kind/dependencies
  description: Pull requests that update a dependency file
  color: 0366d6
-
  name: kind/docs
  description: Improvements or additions to documentation
  color: 0075ca
-
  name: kind/duplicate
  description: This issue or pull request already exists
  color: cfd3d7
-
  name: kind/enhancement
  description: New feature or request
  color: a2eeef
-
  name: kind/invalid
  description: This doesn't seem right
  color: e4e669
-
  name: kind/performance
  description: Performance
  color: "016175"
-
  name: kind/refactoring
  description: Refactoring
  color: ef67c4
-
  name: kind/removal
  description: Removals and Deprecations
  color: 9ae7ea
-
  name: "kind/upstream"
  color: "fbca04"
  description: ""
-
  name: question
  description: Further information is requested
  color: d876e3
-
  name: style
  description: Style
  color: c120e5
-
  name: testing
  description: Testing
  color: b1fc6f
-
  name: wontfix
  description: This will not be worked on
  color: ffffff
