[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.12,<0.13" ]

[project]
name = "mckit-nuclides"
version = "0.6.1.dev2"
description = "Python tools to work with elements and nuclides"
readme = "README.rst"
keywords = [ "abundance", "element", "nuclide" ]
license = { text = "MIT" }
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [ "numpy>=2.4", "polars[numpy]>=1.37" ]
[[project.authors]]
name = "dvp2015"
email = "dmitri_portnov@yahoo.com"
[project.urls]
"Bug Tracker" = "https://github.com/MC-kit/mckit-nuclides/issues"
Changelog = "https://github.com/MC-kit/mckit-nuclides/releases"
documentation = "https://mckit-nuclides.readthedocs.io"
homepage = "https://github.com/MC-kit/mckit-nuclides"
repository = "https://github.com/MC-kit/mckit-nuclides"

[dependency-groups]
dev = [ { include-group = "style" }, { include-group = "test" } ]
test = [
  "pytest>=9",
  "pytest-cov>=7.1",
  "pytest-mock>=3.15",
  "pytest-xdist[psutil]>=3.8",
  "xdoctest>=1.3",
]
docs = [
  "esbonio>=2",
  "rstcheck[sphinx,toml]>=6.2.5",
  "sphinx>=9.1",
  "sphinx-autobuild>=2025.8.25",
  "sphinx-autodoc-typehints>=3.10",
  "sphinx-togglebutton>=0.4",
]
analyze = [ "jupyterlab>=4.5", "jupytext>=1.19" ]
lint = [ "pylint", "pylint-per-file-ignores" ]
mypy = [ "mypy>=1.2", "pep8-naming>=0.12.1", "types-setuptools>=80.9.0.20250529" ]
pre_commit = [ "pre-commit>=4.3" ]
pyright = [ "pyright>=1.1.406" ]
ruff = [ "ruff>=0.0.259" ]
style = [
  "basedpyright>=1.39.9",
  "pyrefly>=1.1.1",
  { include-group = "lint" },
  { include-group = "mypy" },
  { include-group = "pre_commit" },
  { include-group = "pyright" },
  { include-group = "ruff" },
]
typeguard = [ "typeguard>=4.5" ]

[tool.mypy]
files = "src/**/*.py"
follow_imports = "silent"
python_version = "3.14"
strict = true
pretty = true
cache_dir = ".cache/mypy"
warn_unused_configs = true

[tool.coverage.paths]
source = [ "src" ]
[tool.coverage.report]
exclude_lines = [
  "def __repr__",
  "if __name__ == .__main__.:",
  "if 0:",
  "if TYPE_CHECKING:",
  "if self.debug",
  "pragma: no cover",
  "raise AssertionError",
  "raise NotImplementedError",
]
fail_under = 100
ignore_errors = true
omit = [ "**/__init__.py", "**/types.py", "*_tab.py" ]
show_missing = true
skip_covered = true
sort = "Cover"
[tool.coverage.run]
branch = true
omit = [ "**/__init__.py", "*_tab.py", "tools/*.py" ]
parallel = true
source = [ "src" ]

[tool.marimo.runtime]
pythonpath = [ "notebooks", "notebooks/common" ]

[tool.xdoctest]
options = ""
quiet = true

[tool.jupytext]
# https://jupytext.readthedocs.io/en/latest/config.html
# Pair ipynb notebooks to py:percent text notebooks
formats = "ipynb,py:percent"

[tool.creosote]
deps-file = "pyproject.toml"
paths = [ "src" ]
sections = [ "project.dependencies" ]
venvs = [ ".venv" ]

[tool.rstcheck]
ignore_messages = '(Unknown directive type \"cyclopts|todo|(auto(module|class|function))\"\.)'
report_level = "ERROR"
