#!/bin/bash

usage() {
cat << 'EOM'

Helper to bump and commit the project version

Usage:
    bump <version>
    or
    bump --help"

See also:

    uv version --help:

EOM
    uv version --help
}

main() {
    local version="${1:-patch}"
    if [[ "$version" == "--help" ]]; then
        usage
    else
        uv version "$version" && git commit -m "bump: version $(uv version)" pyproject.toml
    fi
}

main "$@"

# vim: set ts=4 sw=4 tw=92 ss=0 ft=sh et ai :
