#!/bin/bash

# set -exu

pyenv virtualenv-delete -f  mckit_nuclides
pyenv virtualenv 3.10.7 mckit_nuclides
pyenv rehash
poetry install
pyenv rehash
python -c "import mckit_nuclides; print(mckit_nuclides.__version__)"


# vim: set ts=4 sw=4 tw=92 ss=0 ft=sh et ai :
