name: Release

env:
  PYTHON_VERSION: '3.13'

on:
  workflow_dispatch:

  release:
    types: ["published"]



concurrency:
  group: ci-release-${{ github.ref }}-1
  cancel-in-progress: true


jobs:
  release:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Check out the repository
        uses: actions/checkout@v4

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install {{ env.PYTHON_VERSION }}

      - name: Build package
        run: |
          uv build

      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        run: uv publish --token=__token__

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v6
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.MCKIT_GITHUB_TOKEN }}
